#!/bin/bash -eu

# shellcheck source=/dev/null
. .env

target="${TEMBOARD_UI_URL#https://}"

cat <<-EOF
- targets:
  - $target
  labels:
    __metrics_path__: /proxy/0.0.0.0/2345/monitoring/metrics
    instance: "postgres0.dev:5432"
    # For PostgreSQL Database dashboard #9628
    kubernetes_namespace: nok8s
    release: norelease
- targets:
  - $target
  labels:
    __metrics_path__: /proxy/0.0.0.0/2346/monitoring/metrics
    instance: "postgres1.dev:5432"
    kubernetes_namespace: nok8s
    release: norelease
EOF
