#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys, signal, os
import ssl

import tornado.ioloop
import tornado.web

from sqlalchemy import create_engine

from ganeshwebui.handlers.base import *
from ganeshwebui.handlers.user import *
from ganeshwebui.handlers.home import *
from ganeshwebui.handlers.notification import *
from ganeshwebui.handlers.manage.user import *
from ganeshwebui.handlers.manage.group import *
from ganeshwebui.handlers.manage.instance import *

from ganeshwebui.async import new_worker_pool
from ganeshwebui.options import ganeshOptions
from ganeshwebui.configuration import Configuration
from ganeshwebui.errors import ConfigurationError, CLIError
from ganeshwebui.logger import get_logger, set_logger_name
from ganeshwebui.daemon import daemonize, httpd_sigterm_handler
from ganeshwebui.pluginsmgmt import load_plugins, plugins_bind_metadata

class CustomTornadoWebApp(tornado.web.Application):
    logger = None
    config = None
    loaded_plugins = []

    def set_logger(self, logger):
        self.logger = logger

    def set_config(self, config):
        self.config = config

    def load_plugins(self, plugin_names):
        plugins = load_plugins(plugin_names, self.config)
        plugins_conf = dict()
        self.loaded_plugins = []
        for key, val in plugins.iteritems():
            self.add_handlers(r'.*', val['routes'])
            plugins_conf[key] = val['configuration']
            if key not in self.loaded_plugins:
                self.loaded_plugins.append(key)
        return plugins_conf

    def log_request(self, handler):
        request_time = 1000.0 * handler.request.request_time()
        log_message = '%d %s %.2fms' % (handler.get_status(), handler._request_summary(), request_time)
        self.logger.info(log_message)

    def create_db_engine(self,):
        dburi = "postgresql://%s:%s@%s:%s/%s" % (
            self.config.repository['user'],
            self.config.repository['password'],
            self.config.repository['host'],
            self.config.repository['port'],
            self.config.repository['dbname']
        )
        self.engine = create_engine(dburi)
        try:
            conn = self.engine.connect()
        except Exception as e:
            self.logger.error("Connection to the database failed for the following reason:")
            self.logger.error("\t%s" % e.message)
            self.logger.error("Please check your configuration.")
            sys.stderr.write("FATAL: %s\n" % e.message)
            exit(1)
        else:
            conn.close()

def main():
    optparser = ganeshOptions(description = "Ganesh web client.")
    (options, _) = optparser.parse_args()
    # Load configuration from the configuration file.
    try:
        config =  Configuration(options.configfile)
        set_logger_name("ganesh")
        logger = get_logger(config)
        logger.info("Starting main process.")
    except (ConfigurationError, ImportError) as e:
        try:
            logger.error(e.message)
        except Exception:
            pass
        sys.stderr.write("FATAL: %s\n" % e.message)
        exit(1)
    # Run ganesh as a background daemon.
    if (options.daemon):
        daemonize(options.pidfile)
    # Dirty way for getting static/ and templates/ absolute paths.
    import ganeshwebui
    base_path = os.path.dirname(ganeshwebui.__file__)
    del ganeshwebui

    # Worker pool creation.
    new_worker_pool(12)

    ssl_ctx = {
        'certfile': config.ganesh['ssl_cert_file'],
        'keyfile': config.ganesh['ssl_key_file']
    }
    handler_conf = {'ssl_ca_cert_file': config.ganesh['ssl_ca_cert_file'], 'template_path': None}
    application = CustomTornadoWebApp(
        [
            (r"/", BaseHandler, handler_conf),
            (r"/home", HomeHandler, handler_conf),
            (r"/login", LoginHandler, handler_conf),
            (r"/logout", LogoutHandler, handler_conf),
            # Manage users
            (r"/manage/users", ManageUserHandler, handler_conf),
            (r"/json/manage/user$", ManageUserJsonHandler, handler_conf),
            (r"/json/manage/user/([0-9a-z\-_\.]{3,16})$", ManageUserJsonHandler, handler_conf),
            (r"/json/manage/delete/user$", ManageDeleteUserJsonHandler, handler_conf),
            (r"/json/manage/all/group/(role|instance)$", ManageGroupAllJsonHandler, handler_conf),
            # Manage groups (users & instances)
            (r"/manage/groups/(role|instance)$", ManageGroupHandler, handler_conf),
            (r"/json/manage/group/(role|instance)$", ManageGroupJsonHandler, handler_conf),
            (r"/json/manage/group/(role|instance)/([0-9a-z\-_\.]{3,16})$", ManageGroupJsonHandler, handler_conf),
            (r"/json/manage/delete/group/(role|instance)$", ManageDeleteGroupJsonHandler, handler_conf),
            # Manage instances
            (r"/manage/instances", ManageInstanceHandler, handler_conf),
            (r"/json/manage/instance$", ManageInstanceJsonHandler, handler_conf),
            (r"/json/manage/instance/([0-9a-zA-Z\-\._:]+)/([0-9]{1,5})$", ManageInstanceJsonHandler, handler_conf),
            (r"/json/manage/delete/instance$", ManageDeleteInstanceJsonHandler, handler_conf),
            # Discover
            (r"/json/discover/instance/([0-9a-zA-Z\-\._:]+)/([0-9]{1,5})$", DiscoverInstanceJsonHandler, handler_conf),
            # Agent Login
            (r"/server/(.*)/([0-9]{1,5})/login", AgentLoginHandler, handler_conf),
            # Notifications
            (r"/server/(.*)/([0-9]{1,5})/notifications", NotificationsHandler, handler_conf),
            (r"/css/(.*)", tornado.web.StaticFileHandler, {'path': base_path+'/static/css'}),
            (r"/codemirror/(.*)", tornado.web.StaticFileHandler, {'path': base_path+'/static/codemirror'}),
            (r"/js/(.*)", tornado.web.StaticFileHandler, {'path': base_path+'/static/js'}),
            (r"/images/(.*)", tornado.web.StaticFileHandler, {'path': base_path+'/static/images'}),
            (r"/fonts/(.*)", tornado.web.StaticFileHandler, {'path': base_path+'/static/fonts'})
        ],
        cookie_secret = config.ganesh['cookie_secret'],
        template_path = base_path+"/templates",
        default_handler_class = Error404Handler
    )
    application.set_config(config)
    application.set_logger(logger)
    config.plugins = application.load_plugins(config.ganesh['plugins'])
    application.create_db_engine()
    plugins_bind_metadata(application.engine, config.ganesh['plugins_orm_engine'])
    # Add signal handlers on SIGTERM.
    signal.signal(signal.SIGTERM, httpd_sigterm_handler)
    application.listen(config.ganesh['port'], address = config.ganesh['address'], ssl_options = ssl_ctx)
    tornado.ioloop.IOLoop.instance().start()

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        sys.stderr.write("FATAL: %s\n" % e.message)
        import traceback
        exc_type, exc_value, exc_traceback = sys.exc_info()
        traceback.print_tb(exc_traceback)
        exit(1)
