#!/bin/sh

### BEGIN INIT INFO
# Provides:          temboard-agent
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start temboard-agent
# Description:       temboard-agent is an administration & monitoring PostgreSQL agent.
### END INIT INFO

# Author: Julien Tachoires <julien.tachoires@dalibo.com>

PATH=/sbin:/bin:/usr/sbin:/usr/bin
NAME=temboard-agent
DAEMON=/usr/bin/$NAME
PIDDIR=/var/run/postgresql
PIDFILE=$PIDDIR/$NAME.pid
OPTS="-c /etc/temboard-agent/$NAME.conf -d -p $PIDFILE"
RUNASUSER="postgres"

# Include temboard-agent defaults if available
if [ -f /etc/default/temboard-agent ] ; then
	. /etc/default/temboard-agent
fi

# Exit if we were uninstalled with the config still there
test -x $DAEMON || exit 0

# Check if configuration exists
test -f $CONF || exit 0

. /lib/lsb/init-functions

SSD="start-stop-daemon --pidfile $PIDFILE --quiet"

case "$1" in
  start)
    log_daemon_msg "Starting" $NAME
    test -d $PIDDIR || install -d -o postgres -g postgres -m 2775 $PIDDIR
    $SSD --exec $DAEMON --start --chuid $RUNASUSER --oknodo -- $OPTS 2> /dev/null
    log_end_msg $?
    ;;

  stop)
    log_daemon_msg "Stopping" $NAME
    $SSD --stop --retry 30 --oknodo
    log_end_msg $?
    ;;

  reload)
    log_daemon_msg "Reloading configuration" $NAME
    $SSD --stop --signal HUP --oknodo
    log_end_msg $?
    ;;

  restart)
	log_daemon_msg "Invoking restart" $NAME
	$0 stop
	$0 start
    ;;

  status)
    status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
    ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|reload|restart|status}"
    exit 1
    ;;
esac

exit 0
