version: '2'

services:
  rhel8: &rhel
    image: dalibo/buildpack-pkg:rockylinux8
    working_dir: /workspace
    environment:
    - VERSION
    - HISTFILE=/workspace/packaging/rpm/.docker-bash-history
    volumes:
    - ../../:/workspace
    command: /workspace/packaging/rpm/build.sh

  rhel7:
    <<: *rhel
    image: dalibo/buildpack-pkg:centos7
