FROM dalibo/temboard-agent:latest

RUN set -ex; \
    apt-get update -y ; \
    mkdir -p /usr/share/man/man1 /usr/share/man/man7 ; \
    apt-get install -y --no-install-recommends \
        docker.io \
        iproute2 \
        python3-pip \
        python3-hupper \
    ; \
    :
