version: '3'

services:
  debian:
    image: buildpack-deps:${CODENAME-jessie}
    environment:
      # See dch(1)
      DEBFULLNAME: ${NAME-Noname}
      DEBEMAIL: ${EMAIL-root@localhost}
    volumes:
    - .:/workspace
    - ../dist/:/dist
    command: /workspace/mkdeb.sh

  rpm:
    image: centos:7
    volumes:
    - ..:/workspace
    command: /workspace/packaging/rpm.sh
