#!/bin/bash
#
# temboard-agent        This starts and stops temboard-agent
#
# chkconfig: 2345 20 80
# description: This starts the Ganesh monitoring agent for PostgreSQL \
#              temboard-agent collects stats on a running PostgreSQL cluster \
#              and allow remote administration of the database cluster.
#
# processname: /usr/bin/temboard-agent
# config: /etc/sysconfig/temboard-agent
# config: /etc/temboard-agent/temboard-agent.conf
# pidfile: /var/run/temboard-agent.pid
#
# Return values according to LSB for all commands but status:
# 0 - success
# 1 - generic or unspecified error
# 2 - invalid or excess argument(s)
# 3 - unimplemented feature (e.g. "reload")
# 4 - insufficient privilege
# 5 - program is not installed
# 6 - program is not configured
# 7 - program is not running
#


PATH=/sbin:/bin:/usr/bin:/usr/sbin

# Source function library.
. /etc/init.d/functions

# Check config
# Find the name of the script
NAME=`basename $0`
if [ ${NAME:0:1} = "S" -o ${NAME:0:1} = "K" ]
then
        NAME=${NAME:3}
fi

DAEMON=/usr/bin/temboard-agent
PIDDIR=/var/run/temboard-agent
PIDFILE=$PIDDIR/$NAME.pid
CONFIG=/etc/temboard-agent/${NAME}.conf
OPTS="-c $CONFIG -d -p $PIDFILE"
RUNASUSER="postgres"

test -f /etc/sysconfig/temboard-agent/${NAME}  && . /etc/sysconfig/temboard-agent/${NAME}

RETVAL=0

start(){
	test -x $DAEMON  || exit 5
	test -f $CONFIG  || exit 6

	echo -n $"Starting $NAME: "

	mkdir -p $PIDDIR
	chown ${RUNASUSER}: $PIDDIR
	cd /tmp
	daemon --user $RUNASUSER --pidfile $PIDFILE $DAEMON "$OPTS"
	RETVAL=$?
	echo
	if test $RETVAL = 0 ; then
		touch /var/lock/subsys/$NAME
	fi
	return $RETVAL
}

stop(){
	echo -n $"Stopping $NAME: "
	killproc -p $PIDFILE temboard-agent
	RETVAL=$?
	echo
	rm -f /var/lock/subsys/$NAME
	return $RETVAL
}

reload(){
	test -f $CONFIG || exit 6
	echo -n $"Reloading configuration: "	
	killproc -p $PIDFILE temboard-agent -HUP
	RETVAL=$?
	echo
	return $RETVAL
}

restart(){
	test -f $CONFIG || exit 6
	stop
	start
}

condrestart(){
	[ -e /var/lock/subsys/$prog ] && restart
	return 0
}


# See how we were called.
case "$1" in
    start)
	start
	;;
    status)
    status -p $PIDFILE temboard-agent
    ;;
    stop)
	stop
	;;
    restart)
	restart
	;;
    reload|force-reload)
	reload
	;;
    condrestart|try-restart)
	condrestart
	;;
    *)
	echo $"Usage: $0 {start|status|stop|restart|condrestart|try-restart|reload|force-reload}"
	RETVAL=3
esac

exit $RETVAL
